### ISSUE TITLE
ik_progressbar.js includes code that is supposed to be added

### ISSUE THREAD

**Issue by jaller94** [learnaria/learnaria.github.io#9]
https://learn.canvas.net/courses/2156/pages/progress-bars?module_item_id=219581

The activity suggestion asks us to add the attribute `tabindex="-1"`, however, it’s already in the code. I assume it was forgotten to be removed.

https://github.com/learnaria/learnaria.github.io/blob/7a468a78b9183e4830fafcfb65ab1b37fa205a1f/assets/ik_progressbar.js#L93-L95

I am not going to submit a pull request as this would cause merge issues for people who worked on the task already.

**Comment by atutor** [comment]
Thanks. We'll hang on to this for now, and add it after the course ends.

**Comment by gregrgay** [comment]
Removed left behind tabindex.
